# Generated by Django 5.2.8 on 2026-03-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(upload_to=""),
        ),
    ]
