# Generated by Django 5.2.8 on 2026-03-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_alter_producto_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="tipo_piel",
            field=models.CharField(
                choices=[
                    ("todos", "Todos"),
                    ("normal", "Normal"),
                    ("seca", "Seca"),
                    ("grasa", "Grasa"),
                    ("mixta", "Mixta"),
                    ("sensible", "Sensible"),
                ],
                default="todos",
                max_length=20,
            ),
        ),
    ]
