# Generated by Django 6.0.3 on 2026-05-12 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='unit_price',
        ),
    ]
