# Generated by Django 6.0.3 on 2026-05-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_remove_cartitem_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_file',
            field=models.FileField(blank=True, null=True, upload_to='cheques/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'Card'), ('transfer', 'Transfer'), ('check', 'Cheque PDF')], max_length=20),
        ),
    ]
