CREATE USER afrodite_usr WITH PASSWORD 'afrodite_pwd';
CREATE DATABASE IF NOT EXISTS afrodite;
GRANT ALL PRIVILEGES ON DATABASE afrodite TO afrodite_usr;
GRANT CONNECT ON DATABASE afrodite TO afrodite_usr;
GRANT USAGE, CREATE ON SCHEMA public TO afrodite_usr;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO afrodite_usr;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO afrodite_usr;