# Generated by Django 6.0.3 on 2026-03-24 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='foto',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='documento_identidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_piel',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('seca', 'Seca'), ('grasa', 'Grasa'), ('mixta', 'Mixta'), ('sensible', 'Sensible')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='DireccionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_predeterminada', models.BooleanField(default=False)),
                ('nombre_destinatario', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('info_adicional', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(default='Colombia', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='usuarios.perfilusuario')),
            ],
        ),
    ]
